pie-framework/pie-ui

- packages/categorize/demo/config.js
- packages/categorize/src/categorize/categories.jsx
- packages/categorize/src/categorize/choices.jsx
- packages/categorize/src/categorize/grid-content.jsx
- packages/categorize/src/categorize/index.jsx
After this it's released I'll update the version and ui for the `pie-elements` repo.
> fix(issue-84): added the left and right positioning for the choices

- jest.config.js
- packages/multiple-choice/src/__tests__/__snapshots__/choice-input-test.jsx.snap
- packages/multiple-choice/src/__tests__/__snapshots__/multiple-choice-test.jsx.snap
- packages/multiple-choice/src/__tests__/choice-input-test.jsx
- packages/multiple-choice/src/__tests__/multiple-choice-test.jsx
- packages/multiple-choice/src/multiple-choice.jsx
Fixes [this](https://github.com/pie-framework/pie-elements/issues/4) issue
> feat(multiple-choice): changed the code in order to be obvious when an user answers partially correct

- packages/categorize/src/categorize/__tests__/index.test.jsx
- packages/categorize/src/categorize/index.jsx
- packages/categorize/src/index.js
Forced the rerender of the html element in order to be able to compile the math in the newly added choices when the user toggles the show correct answers
> fix(categorize): math rendering problem

- packages/ebsr/demo/config.js
- packages/ebsr/package.json
Besides adding missing dependencies I changed ebsr demo mode as well.
> fix(ebsr): Add missing dependencies

- packages/math-inline/demo/config.js
- packages/math-inline/package.json
- packages/math-inline/src/main.jsx
Tons of formatting stuff because of prettier now being integrated into dev workflow. The only real relevant change is related to decimals support (or more specifically in the scenario of disallowed decimals) workflow changes.
> feat(math-inline): decimals support

- packages/graph-lines/package.json
- packages/graph-lines/src/__tests__/graph-line-controls.test.js
- packages/graph-lines/src/__tests__/main.test.js
- packages/graph-lines/src/main.jsx
- yarn.lock
BREAKING CHANGE: `model.model.config` has been updated to `model.graph`.
> feat: Updated model structure and @pie-lib/config-ui version.

- packages/math-inline/src/main.jsx
- packages/math-inline/src/simple-question-block.jsx
Partially resolves [ch1399], [ch1418], [ch1402].
> fix(math-inline): styling fixes

- packages/math-inline/src/__tests__/__snapshots__/main.test.js.snap
- packages/math-inline/src/main.jsx
> fix(math-inline): disable individual answer correctness support for now

- packages/graphing/package.json
> fix: add missing pie-player-events dependency

- packages/image-cloze-association/package.json
- packages/image-cloze-association/src/__tests__/utils-test.js
- packages/image-cloze-association/src/utils-correctness.js
Original description [here](https://app.clubhouse.io/keydatasystems/story/1955/ica-alternate-correct-answers).
> feat: support alternate correct answers

- packages/math-inline/src/main.jsx
- packages/math-inline/src/simple-question-block.jsx
BREAKING CHANGE: Removed response from model.config.response. Use model.config.responses instead.
> fix: Removed model.config.response.

- packages/hotspot/package.json
- packages/hotspot/src/hotspot/index.jsx
Hopefully will fix [this](https://app.clubhouse.io/keydatasystems/story/3124/hot-spot-items-not-rendering-in-ibx) issue.
You can have a look also at these two:
* https://github.com/konvajs/react-konva/issues/365#issuecomment-503248463
* https://github.com/facebook/react/issues/15647#issuecomment-493506786
> fix: react-konva version bump

- packages/hotspot/src/hotspot/container.jsx
- packages/hotspot/src/hotspot/rectangle.jsx
should fix [3536](https://app.clubhouse.io/keydatasystems/story/3536/console-errors-for-hotspot)
> fix console errors

- packages/image-cloze-association/demo/config.js
- packages/image-cloze-association/demo/session.js
- packages/image-cloze-association/src/root.jsx
> fix: image-cloze-association: use session to pre-populate player. 

- packages/match/src/__tests__/main.test.js
- packages/match/src/main.jsx
Solves [ch4802].
Added a test too.
> fix(match): session answer pre-population fix - ch4802

- packages/math-inline/src/__tests__/main.test.js
- packages/math-inline/src/__tests__/simple-question-block.test.js
- packages/math-inline/src/main.jsx
- packages/math-inline/src/simple-question-block.jsx
I asked George for his approval regarding the behaviour that I implemented.
This needs to use the versions released after this is merged: https://github.com/pie-framework/pie-lib/pull/180.
> ch4405: fix: Dismiss the keypad when the response area loses focus.

- packages/extended-text-entry/demo/config.js
- packages/extended-text-entry/src/main.jsx
OT Text size difference in IBX/OT (override font-size of 0.875rem from Typography with 'inherit')
> fix: ch7131:

- packages/multiple-choice/src/main.jsx
Connected with https://github.com/pie-framework/pie-ui/pull/187.
> fix: Issues with EBSR Part Labels in IBX PD-90.

- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/__tests__/main.test.js
- packages/extended-text-entry/src/main.jsx
We need a new version to be used in pie-elements/extended-text-entry
> fix: Excessive white space between the "parts" of "multi-part" Extended Text items. PD-37

- packages/math-inline/src/main.jsx
The onBlur function was not closing the keyboard properly.
> fix: For a particular equation response item, the math editor doesn't work. PD-277

- packages/multiple-choice/src/__tests__/index-test.jsx
- packages/multiple-choice/src/index.js
Remove unintended clue about how many answer choices are correct. PD-253
> fix: Multiple Select should report a question as "answered" as soon as a selection has been made PD-253

- packages/math-inline/src/__tests__/__snapshots__/main.test.js.snap
- packages/math-inline/src/__tests__/main.test.js
- packages/math-inline/src/main.jsx
Alrighty .. this'll put the _inline_ into _math-*inline*_ ;)
> feat(math-inline): keypad moved to a tooltip / pop-up and interaction made truly in-line

- packages/match-list/src/__tests__/index.test.js
- packages/match-list/src/index.js
1. Added fix for the test case where choices index might start from 0. During this case, the existing code was failing.
2. Added test cases for respective scenarios.
> fix: complete is false if 0 is part of session value PD-541

- packages/multiple-choice/src/choice-input.jsx
- packages/multiple-choice/src/multiple-choice.jsx
1.  New utility component Preview prompt changes are replaced for the existing code.
> fix: Authored table borders are not visible in preview PD-342

- packages/multiple-choice/src/multiple-choice.jsx
Mathjax fonts were being overwritten.
> fix(multiple-choice): fix font problem - PD-398

- packages/drawing-response/src/drawing-response/__tests__/drawing-main.test.jsx
- packages/drawing-response/src/drawing-response/drawable-circle.jsx
- packages/drawing-response/src/drawing-response/drawable-rectangle.jsx
https://illuminate.atlassian.net/secure/RapidBoard.jspa?rapidView=439&modal=detail&selectedIssue=PD-895&quickFilter=1805
> fix(drawing-response) update x and y for shapes on drag and drop - PD-895

- package.json
- packages/multi-trait-rubric/src/__tests__/__snapshots__/main-test.jsx.snap
- packages/multi-trait-rubric/src/__tests__/__snapshots__/scale-test.jsx.snap
- packages/multi-trait-rubric/src/__tests__/__snapshots__/trait-test.jsx.snap
- packages/multi-trait-rubric/src/__tests__/main-test.jsx
- packages/multi-trait-rubric/src/__tests__/scale-test.jsx
- packages/multi-trait-rubric/src/__tests__/trait-test.jsx
- packages/multi-trait-rubric/src/main.jsx
- packages/multi-trait-rubric/src/scale.jsx
- packages/multi-trait-rubric/src/trait.jsx
- yarn.lock
Note: we need to release https://github.com/pie-framework/pie-lib/pull/259 first.
I need Andreea’s review on it, since this is connected to multi-trait-rubric author
https://illuminate.atlassian.net/browse/PD-904
> feat(multiple-trait-rubric): update design

- packages/drawing-response/src/drawing-response/__tests__/drawable-helper.test.jsx
- packages/drawing-response/src/drawing-response/__tests__/drawing-main.test.jsx
- packages/drawing-response/src/drawing-response/drawable-helper.jsx
- packages/drawing-response/src/drawing-response/drawable-main.jsx
https://illuminate.atlassian.net/browse/PD-905
https://illuminate.atlassian.net/browse/PD-264
> Fix/drawing-response clear all and undo buttons don't behave as expected PD-264, PD-905

- packages/extended-text-entry/src/__tests__/__snapshots__/main.test.js.snap
- packages/extended-text-entry/src/main.jsx
https://illuminate.atlassian.net/browse/PD-694
> fix(extended-text-entry): expand text entry box - PD-694

- packages/placement-ordering/src/__tests__/ordering.test.js
- packages/placement-ordering/src/ordering.js
- packages/placement-ordering/src/tile.jsx
- packages/placement-ordering/src/tiler.jsx
https://illuminate.atlassian.net/browse/PD-42
> fix(placement-ordering): reposition elements using push instead of swap PD-42
